{% set name = "google-cloud-bigquery" %}
{% set version = "1.11.1" %}
{% set sha256 = "61978e15ec9067fcead664d1d1bc146abd3d77cf12b3576ffae17cf67fafc050" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    # Backport of enum for Python < 3.4.
    - enum34  # [py2k]
    - google-cloud-core >=0.29.0,<0.30dev
    - google-api-core >=1.6.0,<2.0.0dev
    - google-resumable-media >=0.3.1

test:
  imports:
    - google.api_core
    - google.cloud.bigquery

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/bigquery
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python Client for Google BigQuery'
  description: Python idiomatic client for Google BigQuery
  doc_url: https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-usage.html
  dev_url: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/bigquery

extra:
  recipe-maintainers:
    - parthea
    - tswast
