{% set name = "google-cloud-bigquery" %}
{% set version = "1.22.0" %}
{% set build_number = 1 %}
{% set sha256 = "592e839bce506dd5f106099d74038b25b39b89c569aecf57e4ff5d4416ee1b66" %}

package:
  name: "{{ name|lower }}-split"
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  # Conda package for protobuf does not support Python 2.7 on Windows due to
  # requirement on C++ 11. VS 2008 is not supported.
  skip: true  # [win and vc<14]

requirements:
  host:
    - python
    - pip >=18.1
    - setuptools >=34.0.0

outputs:
  - name: {{ name }}
    build:
      number: {{ build_number }}
      noarch: python

    requirements:
      host:
        - python
        - pip >=18.1
        - setuptools >=34.0.0

      run:
        - {{ name }}-core {{ version }}
        - google-cloud-bigquery-storage >=0.6.0,<0.8.0dev
        - ipython >=5.0.0
        - pandas >=0.17.1
        - pyarrow >=0.13.0
        - tqdm >=4.0.0,<=5.0.0dev

  test:
    imports:
      - google.api_core
      - google.cloud.bigquery
      - google.cloud.bigquery.magics
      - google.cloud.bigquery_v2

  about:
    home: https://github.com/googleapis/google-cloud-python/tree/master/bigquery
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: "Batteries-included library for BigQuery API"
    description: |
      {{ name }} installs {{ name }}-core and the extra requirements for
      pandas and pyarrow integrations.

      Supported Python Versions
      -------------------------
      Python >= 3.5

      Deprecated Python Versions
      --------------------------
      Python == 2.7

      - Python 2.7 support will be removed on January 1, 2020.
      - protobuf does not support Visual C++ 2008, windows py27 package not available
    doc_url: https://googleapis.dev/python/bigquery/latest/index.html
    dev_url: https://github.com/googleapis/google-cloud-python/tree/master/bigquery

  - name: {{ name }}-core
    build:
      number: {{ build_number }}
      script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
      skip: True  # [win and vc<14]

    requirements:
      host:
        - python
        - pip >=18.1
        - setuptools >=34.0.0

    run:
      - python
      # Backport of enum for Python < 3.4.
      - enum34  # [py2k]
      - google-cloud-core >=1.0.3,<2.0.0dev
      - google-resumable-media >=0.3.1,<0.6.0dev
      - protobuf >=3.6.0

  test:
    imports:
      - google.api_core
      - google.cloud.bigquery
      - google.cloud.bigquery_v2

  about:
    home: https://github.com/googleapis/google-cloud-python/tree/master/bigquery
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: "Core library for BigQuery API"
    description: |
      {{ name }}-core the core client library for connecting to the BigQuery API.

      Supported Python Versions
      -------------------------
      Python >= 3.5

      Deprecated Python Versions
      --------------------------
      Python == 2.7

      - Python 2.7 support will be removed on January 1, 2020.
      - protobuf does not support Visual C++ 2008, windows py27 package not available
    doc_url: https://googleapis.dev/python/bigquery/latest/index.html
    dev_url: https://github.com/googleapis/google-cloud-python/tree/master/bigquery

extra:
  recipe-maintainers:
    - parthea
    - tswast
