{% set name = "google-cloud-bigquery" %}
{% set version = "3.25.0" %}
{% set build = 1 %}
{% set sha256 = "5b2aff3205a854481117436836ae1403f11f2594e6810a98886afd57eda28509" %}
{% set dev_url = "https://github.com/googleapis/python-bigquery" %}
{% set doc_url = "https://googleapis.dev/python/bigquery/latest" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  # we skip py<38 following along conda-forge, to avoid importlib-metadata
  # which is needed for py37
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

outputs:
  - name: {{ name }}
    build:
      skip: true  # [py<38]
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - {{ pin_subpackage('google-cloud-bigquery-core', exact=True) }}
        # restricting to python >=3.8 to avoid dependency on importlib_metadata for python <3.8
        # bqstorage and pandas extras
        - pyarrow >=3.0.0
        # bqstorage extra
        - google-cloud-bigquery-storage >=2.6.0,<3.0.0dev
        # following conda-forge here, the constraint is more restrictive but valid for all py versions
        - grpcio >=1.49.1,<2.0dev
        # pandas extra
        - pandas >=1.1.0
        - db-dtypes >=0.3.0,<2.0.0dev
        # ipywidgets extra
        - ipywidgets >=7.7.0  # [not py>311]
        # - ipykernel >=6.0.0
        # geopandas extra
        - geopandas >=0.9.0,<1.0dev
        - shapely >=1.8.4,<3.0.0dev
        # ipython extra
        - ipython >=7.23.1,!=8.1.0
        - ipykernel >=6.0.0
        # tqdm extra
        - tqdm >=4.7.4,<=5.0.0dev
        # bigquery_v2 extra
        - proto-plus >=1.15.0,<2.0.0dev
        - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

    test:
      requires:
        - pip
        - pytest
        - freezegun
      source_files:
        - tests/unit
        - tests/__init__.py
      imports:
        - google.api_core
        - google.cloud.bigquery
        - google.cloud.bigquery.client
        - google.cloud.bigquery.dataset
        - google.cloud.bigquery.encryption_configuration
        - google.cloud.bigquery.enums
        - google.cloud.bigquery.external_config
        - google.cloud.bigquery.job
        - google.cloud.bigquery.magics
        - google.cloud.bigquery.model
        - google.cloud.bigquery.query
        - google.cloud.bigquery.retry
        - google.cloud.bigquery.routine
        - google.cloud.bigquery.schema
        - google.cloud.bigquery.table
        - google.cloud.bigquery_v2
        - google.cloud.bigquery_v2.types
      commands:
        - pip check
        # ignore test_magics.py, test_table.py, and test_client.py
        # because they use test_utils, unavailable
        # https://github.com/googleapis/python-bigquery/issues/1758
        - pytest -vv tests/unit --ignore=tests/unit/test_magics.py --ignore=tests/unit/test_table.py --ignore=tests/unit/test_client.py

  - name: {{ name }}-core
    build:
      skip: true  # [py<38]
      script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - google-api-core-grpc >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
        - google-auth >=2.14.1,<3.0.0dev
        - google-cloud-core >=1.6.0,<3.0.0dev
        - google-resumable-media >=0.6.0,<3.0dev
        - packaging >=20.0.0
        - python-dateutil >=2.7.2,<3.0dev
        - requests >=2.21.0,<3.0.0dev

    test:
      requires:
        - pip
      imports:
        - google.api_core
        - google.cloud.bigquery
        - google.cloud.bigquery.client
        - google.cloud.bigquery.dataset
        - google.cloud.bigquery.encryption_configuration
        - google.cloud.bigquery.enums
        - google.cloud.bigquery.external_config
        - google.cloud.bigquery.job
        - google.cloud.bigquery.model
        - google.cloud.bigquery.query
        - google.cloud.bigquery.retry
        - google.cloud.bigquery.routine
        - google.cloud.bigquery.schema
        - google.cloud.bigquery.table
      commands:
        - pip check

about:
  home: {{ dev_url }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: BigQuery API client library
  description: |
    Querying massive datasets can be time consuming and expensive without
    the right hardware and infrastructure. Google BigQuery solves this problem
    by enabling super-fast, SQL queries against append-mostly tables, using
    the processing power of Google's infrastructure.
  doc_url: {{ doc_url }}
  dev_url: {{ dev_url }}

extra:
  recipe-maintainers:
    - chalmerlowe
    - xylar
    - parthea
    - tswast
  skip-lints:
    - wrong_output_script_key
