{% set name = "google-cloud-bigquery" %}
{% set version = "1.8.0" %}
{% set sha256 = "a84c61ea8723f57e89caf0e18e6aa678a1c2df66bb2cb0800dd5c294b46a5912" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - google-cloud-core >=0.28.0,<0.29dev
    - google-api-core >=1.0.0,<2.0.0dev
    - google-resumable-media >=0.2.1

test:
  requires:
    - python 3.6  # work around temporary protobuf issues
  imports:
    - google.cloud.bigquery

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/bigquery
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python Client for Google BigQuery'
  description: Python idiomatic client for Google BigQuery
  doc_url: https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-usage.html
  dev_url: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/bigquery

extra:
  recipe-maintainers:
    - parthea
    - tswast
