{% set name = "google-cloud-bigquery" %}
{% set version = "1.23.0" %}
{% set sha256 = "ca0c550e1d56d16c0394e893d59cd26a7f1eb70eadc559b74f9c20e5f3fe6988" %}
{% set dev_url = "https://github.com/googleapis/google-cloud-python/tree/master/bigquery" %}
{% set doc_url = "https://googleapis.dev/python/bigquery/latest/index.html" %}

package:
  name: "{{ name|lower }}-split"
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # Conda package for protobuf does not support Python 2.7 on Windows due to
  # requirement on C++ 11. VS 2008 is not supported.
  skip: true  # [win and vc<14]

requirements:
  host:
    - python
    - pip >=18.1
    - setuptools >=34.0.0

outputs:
  - name: {{ name }}
    build:
      number: 0
      noarch: python

    requirements:
      host:
        - python
        - pip >=18.1
        - setuptools >=34.0.0

      run:
        - {{ name }}-core {{ version }}
        - google-cloud-bigquery-storage >=0.6.0,<0.8.0dev
        - ipython >=5.0.0
        - pandas >=0.17.1
        - pyarrow >=0.13.0
        - tqdm >=4.0.0,<=5.0.0dev

    test:
      imports:
        - google.api_core
        - google.cloud.bigquery
        - google.cloud.bigquery.client
        - google.cloud.bigquery.dataset
        - google.cloud.bigquery.encryption_configuration
        - google.cloud.bigquery.enums
        - google.cloud.bigquery.external_config
        - google.cloud.bigquery.job
        - google.cloud.bigquery.magics
        - google.cloud.bigquery.model
        - google.cloud.bigquery.query
        - google.cloud.bigquery.retry
        - google.cloud.bigquery.routine
        - google.cloud.bigquery.schema
        - google.cloud.bigquery.table
        - google.cloud.bigquery_v2
        - google.cloud.bigquery_v2.gapic.enums
        - google.cloud.bigquery_v2.types

    about:
      home: {{ dev_url }}
      license: Apache-2.0
      license_family: Apache
      license_file: LICENSE
      summary: "Batteries-included library for BigQuery API"
      description: |
        {{ name }} installs {{ name }}-core and the extra requirements for
        pandas and pyarrow integrations.

        Supported Python Versions
        -------------------------
        Python >= 3.5

        Deprecated Python Versions
        --------------------------
        Python == 2.7

        - Python 2.7 support will be removed on January 1, 2020.
        - protobuf does not support Visual C++ 2008, windows py27 package not available
      doc_url: {{ doc_url }}
      dev_url: {{ dev_url }}

  - name: {{ name }}-core
    build:
      number: 0
      script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
      skip: True  # [win and vc<14]

    requirements:
      host:
        - python
        - pip >=18.1
        - setuptools >=34.0.0

      run:
        - python
        # Backport of enum for Python < 3.4.
        - enum34  # [py2k]
        - google-cloud-core >=1.0.3,<2.0.0dev
        - google-resumable-media >=0.3.1,<0.6.0dev
        - protobuf >=3.6.0

    test:
      imports:
        - google.api_core
        - google.cloud.bigquery
        - google.cloud.bigquery.client
        - google.cloud.bigquery.dataset
        - google.cloud.bigquery.encryption_configuration
        - google.cloud.bigquery.enums
        - google.cloud.bigquery.external_config
        - google.cloud.bigquery.job
        - google.cloud.bigquery.model
        - google.cloud.bigquery.query
        - google.cloud.bigquery.retry
        - google.cloud.bigquery.routine
        - google.cloud.bigquery.schema
        - google.cloud.bigquery.table
        - google.cloud.bigquery_v2
        - google.cloud.bigquery_v2.gapic.enums
        - google.cloud.bigquery_v2.types

    about:
      home: {{ dev_url }}
      license: Apache-2.0
      license_family: Apache
      license_file: LICENSE
      summary: "Core library for BigQuery API"
      description: |
        {{ name }}-core the core client library for connecting to the BigQuery API.

        Supported Python Versions
        -------------------------
        Python >= 3.5

        Deprecated Python Versions
        --------------------------
        Python == 2.7

        - Python 2.7 support will be removed on January 1, 2020.
        - protobuf does not support Visual C++ 2008, windows py27 package not available
      doc_url: {{ doc_url }}
      dev_url: {{ dev_url }}

about:
  home: {{ dev_url }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "BigQuery API client library"
  doc_url: {{ doc_url }}
  dev_url: {{ dev_url }}

extra:
  recipe-maintainers:
    - parthea
    - tswast
