{% set name = "google-cloud-bigquery" %}
{% set version = "1.19.0" %}
{% set sha256 = "f017cc0b7f00f0051da5caccf46519d4f9a52907f43462356dfa19713c3bdf4e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    # Backport of enum for Python < 3.4.
    - enum34  # [py2k]
    - google-cloud-core >=1.0.0,<2.0.0dev
    - google-api-core >=1.6.0,<2.0.0dev
    - google-resumable-media >=0.3.1
    - protobuf >=3.6.0

test:
  imports:
    - google.api_core
    - google.cloud.bigquery
    - google.cloud.bigquery_v2

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/bigquery
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python Client for Google BigQuery'
  description: Python idiomatic client for Google BigQuery
  doc_url: https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-usage.html
  dev_url: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/bigquery

extra:
  recipe-maintainers:
    - parthea
    - tswast
