{% set name = "google-cloud-bigquery" %}
{% set version = "0.26.0" %}
{% set sha256 = "0103ce28b5124cdb915171d08a9439b9742bab15437c8cd37717894900aab4ef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - google-cloud-core >=0.26.0,<0.27dev
    - google-auth >=1.0.0
    - google-resumable-media >=0.2.1
    - requests >=2.0.0

test:
  imports:
    - google.cloud.bigquery

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/bigquery
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python Client for Google BigQuery'
  description: Python idiomatic client for Google BigQuery
  doc_url: https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-usage.html
  dev_url: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/bigquery

extra:
  recipe-maintainers:
    - parthea
    - tswast
