travis:
  secure:
    BINSTAR_TOKEN: LMO/OFpVe61MsyaNzDCm0WzQkjI6FVpBBLqkttqH6kZyvoMT6RzB4jZEM6DQftSrt5AKGeUxF2RlrmopkU2QF798A4re7B34CiFLm2apDu+1JxFZVMCjpmQYFkvv1QVNH2CCrGzyP/3vrYqwJS5vP+IW6NSKE6ttVuXu4EYUdEBMcYgXha39CSO6PgNPe7t1aBC/cq73cyQzoByMaNq6zE0Pp1ZR81zQ4n8YouFSECAVjEoJ8MgG+g2/MGayvI4l0VWewkVRD6QaaHDeXRxPSC2mbPeNO4yoRRKRLmuv1US4kXAo9+xFgUVxFwJeMpv1Lk5REIzIqMjEFGTa5tvKKNZi0ckoS2t0i6pgAqhyiNmoKLFWn4GqlGBtO8tbWTGQmQ9CMSu6Mya9OAx1OxE7W80lpMT/yKBAjop8f0dBqqp82i/3m+u5rxEkmPY/LOkg04T5L00JMsyQHHZ410M4mKxoIr7dyg/uqqVstvfRsHVQcyRpgxdYOOwJXL4C9aU4ONf5McWIekAhVw9GsP9nCE6kv3p89v9j9BmZLzN4X7V2QPaKrvLMuShXhY99l8htGONAjRKqskWRt5DSSczpvP5aZ60L9xqnBOgng0WID5GuK+tbYTZ7R2PsgrnB79s3iXQy3wH/q/NiXgdFZJ7ej3VOjh2E2RzuNqUWF4F2h8o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
