travis:
  secure:
    BINSTAR_TOKEN: DjgA0fp91kX7ftdeZ8GLxw/ejcbenGtGbtV2dqIAG5LzJA/V9iDx4Xi5F06OotVuYV/cOlIpGNJastW7KEJ3+4NtfSo09yWDNMUoXBggXBSWhGA5Y2acEGAKfCDU/wCOPHgaMbo7c+rQSxrLt8FoB60YszvDBDrPMrsESjUsvKEwTaPEKrDCz7lIaxu8ZvPzGYr4Uw8c6RlprZYpmBAR807GAxHhfJn20307wnmCZVjJ9hX0r85x3qbJPF0FzcTRmCEDPBnL9Sdo5ywTy7RAJQ/WJPN5mgvj7hoVYnVME+JAiKo+yZRQoYULawTdQqaqVJRESjBufhbbxVQkz8YvsQESlQxcZzg06RQmi0Jz9tIGuUKTfQghRhML3RxCTdQ7+/ua0TFYmeyAwkBzxhvUoOmCj93MptrOvrKMquz/kJo23ld+Fpgn1T58PROCoRWPiegAXeRd17GP6S1Uodcr08Xdh2N535WaqJ+v8BFYPLxBS4LgYQQstqEP3zK1Q60pQgdta1scAJ1oO9FwCwX2db9HH/IjhKLkQL4S9smd/DwBlHJy6upqwwGGJDoeGXG0PGuUrvl+Fk0Pf7vNhFrBqjv/zvXRhTSutN5QBFBnNVwfBgV8ti80rO2ZGU+fHaQAV/kbk7ll9e7Till1ufWvrNB03kLUBajiSzlAVjjp2aY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
