travis:
  secure:
    BINSTAR_TOKEN: WhaJfqG4s4KrjfxrRQpohfVUnWPV+cjWbIPc0m0AM0/6AHwv1XtvTOO4sb0Vn/Oh0cK3qPsHobITl89C8B6iTyk5kWBlFmUxsDilGx6MCU851VBUt9/L1+FqNXCZWNfMk5lo189OyTLhV3HtDrC8q9YP64EDeK3oVRL0NA/D/CKDGAUrnK58Mk2Uh6CYE7Y0SIJYdClhwMNBt0sYmTfKeVs9ChFZ7HxKDb22MBFFal484LspFixEOUDnW2ECfAeY/U+q38Id3neteHK8D6AVNp07MNj9t34bV2d3UOeT1T/HM5pBeIk3y0hosb870BVkkSyjVBScL3wtkwBvGw0EfdPTkG7wnBuJlh2hXE88NkSJAbPd1T+eqHOFU66CVYr2zNzdRRwtKBtPN+lM2sRjLTjYweO/gzzWO6XblVYzbSRsXyGgvf/BjdYnCoJd/5ial4dkfGTT3hnR/BA4G8vDpBHtYcQgE3pqsg6W4AVI3P2Kp3ZKG48AYDFKM4ZIxzRc1n7BYiYrh1JjkmE0qujpZXUaGxhYD/v+9BiU9GSu3HdEvUYOZ5q8okN53THA8FNmYQJcHPqQ9MfSZ1rUgUGIBahp/j5qeGthh6aZScg1mNHW7z6TdKj24DlCHRZCaeBm7fd+K2guKi/qpqcrpHEcMC0X/NHLa3AyJGfEzsnKjkg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
